name: scraper
description: Package para respagem de dados (scraping) visando facilitar o mesmo.
version: 1.0.0
repository: https://github.com/Skynoshine/Scraper

environment:
  sdk: ^3.4.4

dependencies:
  html: ^0.15.4
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
