name: scraper
description: A Dart package for simplifying data scraping tasks.
version: 1.0.1
repository: https://github.com/Skynoshine/Scraper

environment:
  sdk: ^3.4.4

dependencies:
  html: ^0.15.4
  http: ^1.2.1

dev_dependencies:
  test: ^1.24.0